version: 2
jobs:
  build:
    docker:
      - image: alpine:3.5
    working_directory: ~/pagekit-docs
    branches:
        only:
          - master
    steps:
      - run:
          name: Update Environment
          command: apk update && apk add rsync openssh
      - checkout
      - run:
          name: Transfer Files
          command: rsync -avz --delete --exclude ".git*" . $PAGEKIT_DOC_SERVER